####################################
###  パラメータ設定ファイル            ###
####################################

### カメラ設定
[Camera]

###Pico Flexx
# カメラ画像の横サイズ
image_width = 224 # int
# カメラ画像の縦サイズ
image_height = 171 # int
# カメラの据え付け角度 [deg]
theta_pitch = 30.0 # float
# キャプチャーの速さ [fps]
capture_fps = 30 # int
sensor_type = "TOF"
sensor_id = "0007-0307-0107-1314"

[BugReadOption]
#bug_file_path = "../capture_tmp/bag_0005.bag"
bug_file_path = "/home/inaho-00/デスクトップ/0603/capture_tmp/bag_0151.bag"
start_frame = 0
end_frame = 500
